# Generated by Django 4.2.9 on 2024-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_railcar_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.AddField(
            model_name='railcar',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='myapp.attachment'),
        ),
    ]
