# Generated by Django 4.2.9 on 2024-03-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_demurragecharge_demurrage_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_address', models.CharField(max_length=255)),
                ('seller_contact', models.CharField(max_length=255)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('railcar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.railcar')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
