# Generated by Django 4.2.9 on 2024-04-03 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_railcar_released_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
