# Generated by Django 4.2.9 on 2024-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_railcar_net_weight_railcar_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rate_per_pound',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
