# Generated by Django 4.2.9 on 2024-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_customer_rate_per_pound'),
    ]

    operations = [
        migrations.AddField(
            model_name='demurragecharge',
            name='demurrage_days',
            field=models.IntegerField(default=0),
        ),
    ]
