# Generated by Django 4.2.9 on 2024-05-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_userprofile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='railcar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.railcar'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('railcar', 'issue_date', 'due_date')},
        ),
    ]
