from django .urls import path
from . import views

urlpatterns = [
	path('',views.home,name='home'),
	path('home/', views.home, name='home'),
	path('sign-up/', views.sign_up, name='sign_up'),
	path('outbound/',views.outbound,name='outbound'),
	path('billing/', views.billing, name='billing'),
	path('railcars/', views.railcar_list_in_yard,name='railcar_list_in_yard'),
	path('create_railcar/', views.create_railcar, name='create_railcar'),
	path('edit_railcar/<int:pk>/', views.edit_railcar, name='edit_railcar'),
	path('delete_railcar/<int:pk>/', views.delete_railcar, name='delete_railcar'),
	path('railcar_detail/<int:pk>/', views.railcar_detail, name='railcar_detail'),
	path('release_railcar/<int:pk>/', views.release_railcar, name='release_railcar'),
    path('undo_release_railcar/<int:pk>/', views.undo_release_railcar, name='undo_release_railcar'),
	path('customers_list/', views.customers_list, name='customers_list'),
	path('create_customer/', views.create_customer, name='create_customer'),
    path('edit_customer/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('delete_customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path('customer_detail/<int:pk>/',views.customer_detail, name='customer_detail'),
    path('printable-railcar/<int:pk>/', views.printable_railcar, name='printable_railcar'),
    path('create-invoice/<int:pk>/', views.create_invoice, name='create_invoice'),
	path('invoice/<int:invoice_number>/', views.invoice_final, name='invoice_final'),
    path('send_invoice/<int:invoice_number>/', views.send_invoice, name='send_invoice'),
    path('unpaid_invoice/<int:invoice_number>/', views.unpaid_invoice, name='unpaid_invoice'),
    path('upload_proof/<int:invoice_number>/', views.upload_proof, name='upload_proof'),
    path('create_user_profile/', views.create_user_profile, name='create_user_profile'),
    path('create_standalone_invoice/', views.create_standalone_invoice, name='create_standalone_invoice'),
	path('view_standalone_invoice/<int:invoice_id>/', views.view_standalone_invoice, name='view_standalone_invoice'),
    path('railcar_search/', views.railcar_search, name='railcar_search'),
    path('kosher_wash_list/', views.kosher_wash_list, name='kosher_wash_list'),
    path('inbound_railcar_list/', views.inbound_railcar_list, name='inbound_railcar_list'),
    path('create_kosher_wash/', views.create_kosher_wash, name='create_kosher_wash'),
    path('create_tank/', views.create_tank, name='create_tank'),
    path('view_all_tanks/', views.view_all_tanks, name='view_all_tanks'),
    path('tanks/delete/<int:tank_id>/', views.delete_tank, name='delete_tank'),
    path('kosherwash/<int:pk>/', views.kosherwash_detail, name='kosherwash_detail'),
]

#path('create-post/', views.create_post, name='create_post'),