# Generated by Django 4.2.9 on 2024-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railcar',
            name='track',
            field=models.CharField(default='Default Track', max_length=14),
        ),
    ]
