# Generated by Django 4.2.9 on 2024-03-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attachment_railcar_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railcar',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='railcar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='myapp.railcar'),
        ),
    ]
