# Generated by Django 4.2.9 on 2024-03-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_railcar_attachments_attachment_railcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedRailcar',
            fields=[
                ('railcar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.railcar')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='railcar',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
