# Generated by Django 4.2.9 on 2024-03-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customer_demurrage_free_days_customer_demurrage_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demurragecharge',
            name='free_days',
        ),
    ]
