# Generated by Django 4.2.9 on 2024-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_invoice_delete_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
