# Generated by Django 4.2.9 on 2024-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_invoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='proofs_of_payment/'),
        ),
    ]
