# Generated by Django 4.2.9 on 2024-06-24 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_kosherwash_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosherwash',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
